### ISSUE TITLE
Incompatibility with Symfony v3.3.0-RC1

### ISSUE THREAD

**Issue by hugohenrique** [api-platform/core#1127]
```
Objects returned by Symfony\Component\DependencyInjection\Argument\RewindableGenerator::getIterator() 
must be traversable or implement interface Iterator in.
(which is being imported from "/app/app/config/routing.yml"). 
Make sure there is a loader supporting the "api_platform" type.
```

**Comment by hugohenrique** [comment]
ping @soyuka @dunglas

**Comment by soyuka** [comment]
I've no such issue. Please give more data (composer.json extract, full error etc.).

**Comment by hugohenrique** [comment]
My composer.json
```json
{
  "require": {
    "php": "^7.1",
    "ext-intl": "*",
    "ext-apcu": "^5.1.3",
    "ext-memcached": "^3.0.3",
    "api-platform/core": "dev-master",
    "beberlei/assert": "^2.7",
    "doctrine/doctrine-bundle": "^1.6",
    "doctrine/orm": "^2.5",
    "dunglas/doctrine-json-odm": "dev-master",
    "lcobucci/jwt": "^3.2",
    "nelmio/cors-bundle": "^1.5",
    "ramsey/uuid": "^3.6",
    "ramsey/uuid-doctrine": "^1.2",
    "sensio/framework-extra-bundle": "^3.0.2",
    "simple-bus/symfony-bridge": "^4.1",
    "symfony/monolog-bundle": "^3.0.2",
    "symfony/polyfill-apcu": "^1.0",
    "symfony/swiftmailer-bundle": "^2.3.10",
    "symfony/symfony": "3.3.0-RC1"
  }
}
```

The error message:
```
CRITICAL: Uncaught Exception: Objects returned by Symfony\Component\DependencyInjection\Argument\RewindableGenerator::getIterator() must be traversable or implement interface Iterator in . (which is being imported from "/app/app/config/routing.yml"). Make sure there is a loader supporting the "api_platform" type. {"exception":"[object] (Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): Objects returned by Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator::getIterator() must be traversable or implement interface Iterator in . (which is being imported from \"/app/app/config/routing.yml\"). Make sure there is a loader supporting the \"api_platform\" type. at /app/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php:213, Exception(code: 0): Objects returned by Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator::getIterator() must...
```
```
heritedPropertyMetadataFactory.php(40): ApiPlatform\\Core\\Bridge\\Symfony\\PropertyInfo\\Metadata\\Property\\PropertyInfoPropertyMetadataFactory->create('Domain\\\\Offer\\\\Of...', 'i at /app/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php:213)"} []
```

```
MetadataFactory->create('Domain\\Offer\\Of...', 'i {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Uncaught Exception: Objects returned by Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator::getIterator() must be traversable or implement interface Iterator in /app/vendor/symfony/symfony/src/Symfony/Component/PropertyInfo/PropertyInfoExtractor.php:101\nStack trace:\n#0 /app/vendor/symfony/symfony/src/Symfony/Component/PropertyInfo/PropertyInfoExtractor.php(55): Symfony\\Component\\PropertyInfo\\PropertyInfoExtractor->extract(Object(Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator), 'getShortDescrip...', Array)\n#1 /app/vendor/api-platform/core/src/Bridge/Symfony/PropertyInfo/Metadata/Property/PropertyInfoPropertyMetadataFactory.php(59): Symfony\\Component\\PropertyInfo\\PropertyInfoExtractor->getShortDescription('Domain\\\\Offer\\\\Of...', 'id'...
```

**Comment by soyuka** [comment]
Can you try:

```
        "symfony/symfony": "^3.3@beta",
```

?

**Comment by hugohenrique** [comment]
I'll try

**Comment by hugohenrique** [comment]
Remains errors:
```
FileLoaderLoadException in FileLoader.php line 175:
Objects returned by Symfony\Component\DependencyInjection\Argument\RewindableGenerator::getIterator() must be traversable or implement interface Iterator in . (which is being imported from "/app/app/config/routing.yml"). Make sure there is a loader supporting the "api_platform" type.
```

```
Exception in PropertyInfoExtractor.php line 101:
Objects returned by Symfony\Component\DependencyInjection\Argument\RewindableGenerator::getIterator() must be traversable or implement interface Iterator
```

```
Exception in PropertyInfoExtractor.php line 101:
Objects returned by Symfony\Component\DependencyInjection\Argument\RewindableGenerator::getIterator() must be traversable or implement interface Iterator
```

**Comment by meyerbaptiste** [comment]
I really can't reproduce these errors too...

**Comment by hugohenrique** [comment]
My configuration to api_platform:
```yaml
api_platform:
    enable_swagger: true
    eager_loading:
        force_eager: false
        max_joins: 20
    loader_paths:
        yaml: ["%kernel.root_dir%/../app/config/api_resources.yml"]
```

**Comment by meyerbaptiste** [comment]
Nor with this configuration. Can you provide a small public project which reproduces these errors?

**Comment by hugohenrique** [comment]
Yes, I will make this

**Comment by hugohenrique** [comment]
Here: https://github.com/hugohenrique/api-platform-incompatibility

**Comment by hugohenrique** [comment]
Important to comment that if you run ```composer install``` it works
but if run ```composer install --prefer-dist --no-dev``` don't work.

**Comment by hugohenrique** [comment]
ping @soyuka

**Comment by hugohenrique** [comment]
@soyuka, it seems like the problem is happening because of this change. 
https://github.com/symfony/symfony/pull/21654

**Comment by hugohenrique** [comment]
Can anyone help me with this? I'm still trying to understand what's happening.
@dunglas @soyuka @teohhanhui

**Comment by meyerbaptiste** [comment]
Okay, I got it @hugohenrique...

Your problem is due to a bug in Symfony with the `Symfony\Component\DependencyInjection\Argument\RewindableGenerator` and `Symfony\Component\DependencyInjection\Dumper\PhpDumper` classes.

You can temporarily fix it by requiring `phpdocumentor/reflection-docblock:^3.0` package to your `composer.json` file.

I'll open an issue on the Symfony bug tracker.

**Comment by hugohenrique** [comment]
@meyerbaptiste, thank you very much! The problem was resolved with your suggestion!
How did you come to that conclusion? :)

**Comment by meyerbaptiste** [comment]
After debugging all the morning! 😰 

Issue is here: https://github.com/symfony/symfony/issues/22780

**Comment by hugohenrique** [comment]
Thanks again, @meyerbaptiste!
As this problem is related to Symfony I will close this issue.

**Comment by meyerbaptiste** [comment]
The patch was merged in Symfony @hugohenrique. So if you want to remove `phpdocumentor/reflection-docblock` just run `composer remove phpdocumentor/reflection-docblock && composer update symfony/symfony`.
