### ISSUE TITLE
Missing symfony/http-client dependency

### ISSUE THREAD

**Issue by vincentchalamon** [api-platform/core#2955]
While fixing https://github.com/api-platform/demo/pull/120, I needed to upgrade api-platform/core to dev-master. During the test workflow, the `docker-compose exec php bin/console doctrine:schema:drop --env=test --force` command throws the following error:
```
Fatal error: During class fetch: Uncaught ReflectionException: Class Symfony\Component\HttpClient\HttpClientTrait not found in /srv/api/vendor/api-platform/core/src/Bridge/Symfony/Bundle/Test/Client.php:34
Stack trace:
#0 /srv/api/vendor/symfony/debug/DebugClassLoader.php(160): require('/srv/api/vendor...')
#1 [internal function]: Symfony\Component\Debug\DebugClassLoader->loadClass('ApiPlatform\\Cor...')
#2 [internal function]: spl_autoload_call('ApiPlatform\\Cor...')
#3 /srv/api/vendor/symfony/config/Resource/ClassExistenceResource.php(78): class_exists('ApiPlatform\\Cor...')
#4 /srv/api/vendor/symfony/dependency-injection/ContainerBuilder.php(353): Symfony\Component\Config\Resource\ClassExistenceResource->isFresh(0)
#5 /srv/api/vendor/symfony/dependency-injection/Dumper/PhpDumper.php(399): Symfony\Component\DependencyInjection\ContainerBuilder->getReflectionClass('ApiPlatform\\Cor...', false)
#6 /srv/api/vendor/symfony/dependency-injection/Dumper/PhpDumper.php(461): Symfony\Component\DependencyInjection\Dumper\PhpDumper in /srv/api/vendor/api-platform/core/src/Bridge/Symfony/Bundle/Test/Client.php on line 34
```

**Comment by teohhanhui** [comment]
This is https://github.com/symfony/symfony/issues/32395
