### ISSUE TITLE
Route with custom uriTemplate stopped working after upgrade to 3.0.5

### ISSUE THREAD

**Issue by acirulis** [api-platform/core#5234]
**API Platform version(s) affected**: 3.0.5

**Description**  
I have a resource with following config:
```php
#[ApiResource(
    shortName: 'Inventory',
    operations: [
        new GetCollection(
            uriTemplate: '/warehouses/{warehouseId}/inventory',
        ),
        new Get(
            uriTemplate: '/warehouses/{warehouseId}/inventory/{id}',
        ),
    ],
    uriVariables: [
        'warehouseId' => new Link(
            fromProperty: 'id',
            fromClass: WarehouseResource::class,
        )
    ],
    normalizationContext: ['groups' => ['inventory:read']],
    denormalizationContext: ['groups' => ['inventory:write']],
    provider: InventoryResourceProvider::class,
)]
...
```

After upgrade to v3.0.5, GetCollection endpoint dies with error ( "Unable to generate an IRI for the item of type \"App\\ApiResource\\InventoryResource\"",)

Stack:
```php

"Symfony\Component\Routing\Exception\MissingMandatoryParametersException: Some mandatory parameters are missing ("id") to generate a URL for route "_api_/warehouses/{warehouseId}/inventory/{id}_get". in /var/www/html/api/vendor/symfony/routing/Generator/UrlGenerator.php:175
Stack trace:
#0 /var/www/html/api/vendor/symfony/routing/Generator/CompiledUrlGenerator.php(67): Symfony\Component\Routing\Generator\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, '_api_/warehouse...', 1, Array, Array)
#1 /var/www/html/api/vendor/symfony/routing/Router.php(225): Symfony\Component\Routing\Generator\CompiledUrlGenerator->generate('_api_/warehouse...', Array, 1)
#2 /var/www/html/api/vendor/api-platform/core/src/Symfony/Routing/Router.php(102): Symfony\Component\Routing\Router->generate('_api_/warehouse...', Array, 1)
#3 /var/www/html/api/vendor/api-platform/core/src/Symfony/Routing/IriConverter.php(187): ApiPlatform\Symfony\Routing\Router->generate('_api_/warehouse...', Array, 1)
#4 /var/www/html/api/vendor/api-pl"
```

**Additional Context**  
Worked before 3.0.5

**Comment by Aerendir** [comment]
May be linked to #5235

**Comment by soyuka** [comment]
https://github.com/api-platform/core/pull/5217 

Indeed your URI variables configuration is wrong on the Get operation:

```
#[ApiResource(
    shortName: 'Inventory',
    operations: [
        new GetCollection(
            uriTemplate: '/warehouses/{warehouseId}/inventory',
        ),
        new Get(
            uriTemplate: '/warehouses/{warehouseId}/inventory/{id}',
            uriVariables: [
                'warehouseId' => new Link(
                    fromProperty: 'id',
                    fromClass: WarehouseResource::class,
                ),
                'id' => new Link(identifiers: ['id'], fromClass: self::class)
            ],
        ),
    ],
    uriVariables: [
        'warehouseId' => new Link(
            fromProperty: 'id',
            fromClass: WarehouseResource::class,
        )
    ],
    normalizationContext: ['groups' => ['inventory:read']],
    denormalizationContext: ['groups' => ['inventory:write']],
    provider: InventoryResourceProvider::class,
)]
```

The magic that was working before is a bug and it shouldn't have been working at all.

**Comment by soyuka** [comment]
Sorry about this, update to 3.0.6.

**Comment by Babyd12** [comment]
if you used the API platform: 3.0.5
the value expected by uriTemplate for the parameter is {id}
if you use {userId} it will no longer work.

This is what I deduced after two days of debugging.
Use:   uriTemplate: '/password/reset/{id}',
