### ISSUE TITLE
[Swagger] Undefined array key "$ref" since 3.1.6

### ISSUE THREAD

**Issue by DeLm0re** [api-platform/core#5501]
**API Platform version(s) affected**: 3.1.6

**Description**  

Since this new version, it is impossible to acces my swagger documentation via /api 

For instance for a simple entrypoint like this one 

```php
new Metadata\GetCollection(
            routeName: 'api_get_user',
            openapi: new Model\Operation(
                responses: [
                    Response::HTTP_UNAUTHORIZED => new Model\Response(ResponseMessage::UNAUTHORIZED),
                ],
                parameters: [
                    new Model\Parameter(
                        name: 'id',
                        in: 'query',
                        description: 'The User identifier',
                        schema: ['type' => 'object'],
                        style: 'deepObject',
                        explode: true,
                    ),
                    new Model\Parameter(
                        name: 'name|lastname|username',
                        in: 'query',
                        description: 'The User denomination',
                        schema: ['type' => 'object'],
                        style: 'deepObject',
                        explode: true,
                    ),
                ],
            ),
        ),
```

cause 500 error

![Capture d’écran 2023-03-27 à 18 12 04](https://user-images.githubusercontent.com/18305718/228000591-7f27aed3-9347-43db-8f1f-c21b2a4daf6d.png)

**Additional Context**  

I'm working on MacOs, Php 8.1, Symfony 6.2.7, doctrine-bundle 2.9.
Everything is working fine on 3.1.5

**Comment by cyrilverloop** [comment]
Hi, same problem since 3.1.6 with PHP 8.2.4 and Symfony 6.2.7.

**Comment by hurtreljulie** [comment]
Same problem here

**Comment by j-schumann** [comment]
Same problem here. This happens only for some schemas as far as I can tell, they are created in 
L155 of the TypeFactory
```
$subSchema = $this->schemaFactory->buildSchema($className, $format, Schema::TYPE_OUTPUT, null, $subSchema, $serializerContext, false);
```
without the $ref: https://i.imgur.com/0xVVun6.png

Maybe related to Resources that have no (exposed) endpoints and thus no definition (yet)?
E.g. it happens for me with embeded Images that are annotated with:

```
#[ApiResource(
    types: 'https://schema.org/MediaObject',
    operations: [
        new NotExposed(),
    ],
)]
```
  
Also: I'm very suprised about the introduced BC break with that patch version: `ApiPlatform\OpenApi\Factory\OpenApiFactory::OPENAPI_DEFINITION_NAME` no longer exists (but is moved to the SchemaFactory) and causes runtime errors in my code.
Shouldn't this be marked deprecated until the next major and refer to the `SchemaFactory::OPENAPI_DEFINITION_NAME` for the time being? 
I use this constant in my custom ResourceMetadataCollectionFactory wrapper, and it was not marked "internal" before (and is not now) .

**Comment by soyuka** [comment]
Hi, not sure from where the problem occurs: 
https://github.com/api-platform/core/commit/e471622271dc8fe1b31adfd6c8232693e354c004 is the change we made to the Schema. 

Can someone check if your use case breaks after introducing this commit? Also please send me a full stack trace! 

> Also: I'm very suprised about the introduced BC break with that patch version: ApiPlatform\OpenApi\Factory\OpenApiFactory::OPENAPI_DEFINITION_NAME no longer exists (but is moved to the SchemaFactory) and causes runtime errors in my code.

My fault, I'll reintroduce this I shouldn't have removed it.

**Comment by DeLm0re** [comment]
Here is the stack trace I have for my part

**Warning: Undefined array key "$ref"** 

```
#0 /vendor/api-platform/core/src/JsonSchema/TypeFactory.php(75): ApiPlatform\JsonSchema\TypeFactory->getClassType('App\\Entity\\Acti...', true, 'json', true, Array, Object(ApiPlatform\JsonSchema\Schema))
#1 /vendor/api-platform/core/src/JsonSchema/TypeFactory.php(66): ApiPlatform\JsonSchema\TypeFactory->makeBasicType(Object(Symfony\Component\PropertyInfo\Type), 'json', true, Array, Object(ApiPlatform\JsonSchema\Schema))
#2 /vendor/api-platform/core/src/JsonSchema/SchemaFactory.php(216): ApiPlatform\JsonSchema\TypeFactory->getType(Object(Symfony\Component\PropertyInfo\Type), 'json', true, Array, Object(ApiPlatform\JsonSchema\Schema))
#3 /vendor/api-platform/core/src/JsonSchema/SchemaFactory.php(136): ApiPlatform\JsonSchema\SchemaFactory->buildPropertySchema(Object(ApiPlatform\JsonSchema\Schema), 'ActivitySector-...', 'mainActivitySec...', Object(ApiPlatform\Metadata\ApiProperty), Array, 'json')
#4 /vendor/api-platform/core/src/Hydra/JsonSchema/SchemaFactory.php(70): ApiPlatform\JsonSchema\SchemaFactory->buildSchema('App\\Entity\\Acti...', 'json', 'output', Object(ApiPlatform\Metadata\GetCollection), Object(ApiPlatform\JsonSchema\Schema), Array, true)
#5 /vendor/api-platform/core/src/OpenApi/Factory/OpenApiFactory.php(237): ApiPlatform\Hydra\JsonSchema\SchemaFactory->buildSchema('App\\Entity\\Acti...', 'json', 'output', Object(ApiPlatform\Metadata\GetCollection), Object(ApiPlatform\JsonSchema\Schema), NULL, true)
#6 /vendor/api-platform/core/src/OpenApi/Factory/OpenApiFactory.php(91): ApiPlatform\OpenApi\Factory\OpenApiFactory->collectPaths(Object(Linkweb\Annotation\ApiResource), Object(ApiPlatform\Metadata\Resource\ResourceMetadataCollection), Object(ApiPlatform\OpenApi\Model\Paths), Object(ArrayObject))
#7 /vendor/api-platform/core/src/Symfony/Bundle/SwaggerUi/SwaggerUiAction.php(45): ApiPlatform\OpenApi\Factory\OpenApiFactory->__invoke(Array)
#8 /vendor/symfony/http-kernel/HttpKernel.php(163): ApiPlatform\Symfony\Bundle\SwaggerUi\SwaggerUiAction->__invoke(Object(Symfony\Component\HttpFoundation\Request))
#9 /vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#10 /vendor/symfony/http-kernel/Kernel.php(184): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#12 /vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
#13 /public/index.php(5): require_once('/Users/dev/Docu...')
#14 {main}
```

**Comment by DeLm0re** [comment]
@soyuka As @paullallier said, a simple resource having `#[ApiResource(operations: [])]` is enought for the bug to appear.

Also notice that, as @cyrilverloop pointed out, I can confirm that the bug only appears in `dev` environment.

**Comment by DeLm0re** [comment]
@soyuka After some digging & xdebug, it seems that the error occurs here

https://github.com/api-platform/core/blob/ccef472cade42b189fa8cb7793e27fad1349e289/src/JsonSchema/TypeFactory.php#L146-L157

Because `$subSchema` is not an array at the return point but a `ApiPlatform\JsonSchema\Schema` or at least the code can not access the index `$ref`

**Comment by twisted1919** [comment]
@DeLm0re / @soyuka - the above is my case as well, I had to temporary modify the code to return:
```php
return ['$ref' => $subSchema['$ref'] ?? '']; 

```
Only to be able to continue with my daily development tasks.

**Comment by paullallier** [comment]
> A simple resource having `#[ApiResource(operations: [])]` is **NOT enought** for the bug to appear.

Odd.  It definitely triggers it for me, but maybe we have something else different in our setups.  You're example is definite a more realistic one though.

**Comment by soyuka** [comment]
can someone try the following patch:

```diff
diff --git a/src/JsonSchema/SchemaFactory.php b/src/JsonSchema/SchemaFactory.php
index 1f7584719..76921ab91 100644
--- a/src/JsonSchema/SchemaFactory.php
+++ b/src/JsonSchema/SchemaFactory.php
@@ -317,8 +317,10 @@ private function getMetadata(string $className, string $type = Schema::TYPE_OUTP
         ];
     }
 
-    private function findOperationForType(ResourceMetadataCollection $resourceMetadataCollection, string $type, Operation $operation)
+    private function findOperationForType(ResourceMetadataCollection $resourceMetadataCollection, string $type, Operation $operation): HttpOperation
     {
+        $operation = new HttpOperation();
+
         // Find the operation and use the first one that matches criterias
         foreach ($resourceMetadataCollection as $resourceMetadata) {
             foreach ($resourceMetadata->getOperations() ?? [] as $op) {
```

Also can someone with the problem ping me on the Symfony slack? I still can't reproduce a failing test case and it's hard for me to find the correct fix. Just using an empty `$ref` is not good enough, we should find that `$ref`.

**Comment by Andreas-Sommer** [comment]
> > A simple resource having `#[ApiResource(operations: [])]` is **NOT enought** for the bug to appear.
> 
> Odd. It definitely triggers it for me, but maybe we have something else different in our setups. Your example is definitely a more realistic one though.

Is there a better way removing operations?
I am using some API resources as a subresources without any operations.

**Comment by soyuka** [comment]
I've a reproducer thanks to @paullallier, trying to release a patch by  the end of the day!

**Comment by cyrilverloop** [comment]
3.1.7 seems to fix the problem for me. Thanks !
